### ISSUE TITLE
rename "django_htmx" templatetag to "htmx"

### ISSUE THREAD

**Issue by nerdoc** [adamchainz/django-htmx#127]
### Description

It's just a small change, and would even break compatibility...
But I dare to suggest renaming it to "htmx"  - just because `{% load htmx %}` sounds clearer.
There is already a `djhtmx` library which hast this tag - but anyway, both won't be installed together anyway.

**Comment by adamchainz** [comment]
I would rather be more explicit, and not cause churn.
