### ISSUE TITLE
readme should be clearer about how to use templatetag

### ISSUE THREAD

**Issue by nerdoc** [adamchainz/django-htmx#128]
### Package Version
git

### Description

In the [readme file](https://github.com/adamchainz/django-htmx#extension-script) there is a hint how to use the templatetag:

For *Django Templates*, load and use the template tag:
```django
{% load django_htmx %}
{% django_htmx_script %}
```
It's not clear: do I need to include `{% django_htmx_script %}` too in every (sub)template where I want to use htmx? Or is it ok to do it once in the base template?
For `{{ django_htmx_script() }}` you make it clearer, it's only needed in the base template.

Maybe you could improve that, for beginners...

**Comment by nerdoc** [comment]
Oh, sorry to have asked, didn't want to disturb you. If you think your docs are perfect, that's fine for me. Open Source is about community, and if you don't want to make things more clearly, good. It's not about "every detail", and no, your line with "you probably want to" is not clear. I can look at the [script](https://github.com/adamchainz/django-htmx/blob/main/src/django_htmx/jinja.py) myself, and see what it does. Yust wanted to help. But ok, it's your code.

**Comment by adamchainz** [comment]
Please don't take things so personally.

I've tweaked the wording in #129. I removed "probably" to be more assertive, and removed "in your base template" because that does presume a certain layout.

**Comment by nerdoc** [comment]
That's nice - didn't want to bump you neither... Thanks for telling me. And for improving the docs ;-)
