### ISSUE TITLE
htmx decorator

### ISSUE THREAD

**Issue by rtpm** [adamchainz/django-htmx#147]
### Description

Hello, maybe you could add a htmx decorator which renders different template if using `TemplateResponse` in the view ?

Here's an example, from Luke's repo:
https://gitlab.com/learnscripture/learnscripture.net/-/blob/master/learnscripture/decorators.py#L80

Thanks!

**Comment by adamchainz** [comment]
There are many approaches to partial rendering. I don't want to encode just one of them in a decorator or CBV. I want to keep this library restricted to htmx-level stuff that you can build your own helpers out of if you wish.
