### ISSUE TITLE
Readme isn’t explcit enough

### ISSUE THREAD

**Issue by Ladet02** [adamchainz/django-htmx#149]
### Description

I would suggest a better readme by adding examples (use case) and snippets, to make it more beginner friendly.

**Comment by adamchainz** [comment]
Can you make a PR rather than a one line issue?

**Comment by adamchainz** [comment]
Did you check out the example app

**Comment by Ladet02** [comment]
No I haven’t, I would though. But I’m saying not everyone who checks the package would want to go through the example app.

**Comment by Nebucatnetzer** [comment]
One thing which I tripped over was that I had to add htmx to the static files by myself.
Maybe the README could be extended to mention that?
Or explicitly state what it tries to do and what it doesn't try to do?

**Comment by adamchainz** [comment]
I've added a note about setting up htmx in #172.
