### ISSUE TITLE
hx-headers raises an error: Unexpected identifier 'find' (anonymous function) (htmx.js:1)

### ISSUE THREAD

**Issue by julzhk** [adamchainz/django-htmx#166]
### Python Version

3.10

### Django Version

3.2.7

### Package Version

1.6.0

### Description

Firstly: thank-you for your hard work on the package and the documentation. 
I have a bit of a problem with the hx-headers / CSRF example. 
I've set DEBUG to True and use static locally boilerplate & installed htmx using the script - everything's in place and working. Css, 

However, when I fill in the form, the form GETs from  http://127.0.0.1:8080/csrf-demo/?number=5. It does not do a POST to /csrf-demo/checker/ as I would expect it to. 

And I get a [Error] SyntaxError: Unexpected identifier 'find' (anonymous function) (htmx.js:1)

I'm sure I'll figure it out eventually, but if you have any suggestions I'd be most grateful.

**Comment by julzhk** [comment]
Solved: I ran this to install htmx:
`python download_htmx.py 3.7.0 

It created an htmx.js file in the static folder but it had an error message in it (package not found), and no javascript. doh.

I should have run : python download_htmx.py 1.6.1
And now it works perfectly.

**Comment by adamchainz** [comment]
`download_htmx.py` is not intended for use, it's just a quick script to help maintain the example app. It has no error handling etc.

I have added a note to the script in #168.
