### ISSUE TITLE
[Question] Is there a CONTRIBUTING.md that covers how to contribute to this project?

### ISSUE THREAD

**Issue by simkimsia** [adamchainz/django-htmx#17]
Also, are you aware of a new beta feature that allows discussions in a separate tab?  https://docs.github.com/pt/free-pro-team@latest/discussions I think questions like mine would be better off in discussions to avoid polluting issues

**Comment by adamchainz** [comment]
I'm aware of discussions but I don't want to activate it yet. I'm afraid it will cause discussions to become *more* splintered between issues and discussions. Most of my open source projects are intentionally small and limited.

To answer your question, no I don't have any contribution guidelines at the moment but I will get around to writing some to cover all my repos. Most of the stylistic things that need enforcing are covered by pre-commit when you open a PR anyway.
