### ISSUE TITLE
Using DjangoJSONEncoder in json.dumps

### ISSUE THREAD

**Issue by CleitonDeLima** [adamchainz/django-htmx#180]
### Description

Hi,

It might be interesting to use [DjangoJSONEncoder](https://github.com/django/django/blob/7346c288e307e1821e3ceb757d686c9bd879389c/django/core/serializers/json.py#L77) when dumping a dict in trigger_client_event.

https://github.com/adamchainz/django-htmx/blob/825e3493aa5089e7beb44a4c20d92b9e2a0b25f4/src/django_htmx/http.py#L63

```python
response[header] = json.dumps(data, cls=DjangoJSONEncoder)
```

**Comment by adamchainz** [comment]
> It might be interesting

I guess it would make sense to fit in with Django, but do you have a use case?

Feel free to open a PR. Please do add a test and changelog note.

**Comment by CleitonDeLima** [comment]
> I guess it would make sense to fit in with Django, but do you have a use case?

Shen it is necessary to serialize data of type `date` or `decimal`, which `json.dumps` does not support, `DjangoJSONEncoder` can help in these cases.

I did a [PR](https://github.com/adamchainz/django-htmx/pull/182) with a test of this.
