### ISSUE TITLE
Add X-CSRFToken via htmx:configRequest event

### ISSUE THREAD

**Issue by valberg** [adamchainz/django-htmx#196]
### Description

I wanted to hear if there is any interest in adding the X-CSRFToken to every HTMX request by grabbing the `htmx:configRequest` event?

I've had quite a good success by including the following in my base templates:

```html
<script>
    // Make sure we have csrf_token in HTMX requests
    document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    })
</script>
```

Including this in django-htmx by either modifying django-htmx.js (and removing the non-debug guard in jinja.py) could be one way of doing it. Another could be a seperate `{% htmx_csrf_header %}` template tag.

Any thoughts?

**Comment by adamchainz** [comment]
There's no need for any Javascript. You can use `hx-headers` - this is already documented in the example project CSRF demo:

https://github.com/adamchainz/django-htmx/blob/2c1f95b4bf6655cd6424c1c5b51ab3c135300915/example/example/templates/csrf-demo.html#L4-L22

I'm further adding a docs page in the Docs PR: https://github.com/adamchainz/django-htmx/pull/194/files#diff-3d3c9ddabd7ba7f0fa458351d17598c03548245af53febc5c09fd829bb42dea1

**Comment by valberg** [comment]
Oh yes I knew that :) But having to add that to each html tag where you want to do htmx requests "gets tedious". I started using hx-headers initially but kept on forgetting them, which is why I turned to the configRequest event - to remove friction :)

Anyway, I'll consider this as out-of-scope for django-htmx :)
