### ISSUE TITLE
Add an utility property for the non boosted htmx request case

### ISSUE THREAD

**Issue by yahya-abou-imran** [adamchainz/django-htmx#222]
### Description

Hi Adam!
Thanks for this useful package.

Here is a pattern that could be useful in several places (views or templates) :
```python
if self.request.htmx and not self.request.htmx.boosted:
```
It helps pointing out when we really want to use a fragment template.
A real example [here](https://github.com/gone/animelister/blob/32afacb63662e7cbff562040c5d28018c3c90512/animelister/util/views.py#L23).

It could be interesting to add it a wrapper property, don’t know how to name it though (`unboosted`???)...  

If I would like to add it manually, it would mean patching `HtmxDetail`, or make a custom middleware with a subclass of `HtmxDetail`…

**Comment by adamchainz** [comment]
Hey!

I am not sure what you're doing is particularly common... normally with htmx I write views that are for htmx only. I haven't considered *combining* both boosting and fragment fetching for the same view.

Also, it's not a particularly complicated expression that you'd like to simplify, and in your example you only use it in one place?

I would like to see more people say they have this use case before considering adding it. For now you could add a custom subclass and middleware in your project as I wrote in #223.

Thanks,

Adam

**Comment by yahya-abou-imran** [comment]
I have a project with hundreds of CBVs, and I was’nt using htmx at the beginning.  
Rewrite everything from scratch would be a pain, so I was searching a solution to start using htmx gradually.  
A discussion in the django channel of the htmx discord with people help me think about solutions.  

But yes, you are right, keeping `django_htmx` the more minimalist possible and non opinionated is probably better.

Thank you.
