### ISSUE TITLE
Customize HtmxDetail through a subclass

### ISSUE THREAD

**Issue by yahya-abou-imran** [adamchainz/django-htmx#223]
### Description

Building on #222, it would be intersting to let user declare a subclass of `HtmxDetail` with helpers and have a setting variable pointing out to the location:
`HTMX_DETAIL_CLASS = "here.is.my.HtmxDetailSubClass"`

**Comment by adamchainz** [comment]
If you want to use a custom class, you can subclass `HtmxDetails` and write your own middleware that uses it. The middleware is really simple, I don't think it's worth adding an extension point.
