### ISSUE TITLE
HTMXPartialTemplateMixin feature

### ISSUE THREAD

**Issue by lolrenx** [adamchainz/django-htmx#233]
### Description

the frequent following pattern could be embedded in a mixin à la django : 
```python
    template_name = "survey/question_list.html"

    def get_template_name(self, request):
        if request.htmx:
            return "survey/question_list_partial.html"
```

proposed mixin : 

```python
class HTMXPartialTemplateMixin:
    """
    A template mixin that appends _partial to the template name in case of
    a partial request via HTMX.
    this default behaviour can be overridden by setting the
    partial_template_name class attribute.
    """

    partial_template_name = None

    def get_template_name(self, request, **kwargs):
        if not request.htmx:
            return self.template_name
        if self.partial_template_name:
            return self.partial_template_name
        else :
            return self.template_name.replace(".html", "_partial.html")
```

then used like so : 

```python
class Questionlist(ListView, HTMXPartialTemplateMixin):
    template_name = "survey/question_list.html"

    def get(self, request):
        template_name = self.get_template_name(request)
```

This idea is credited to @malmiteria, it makes the ol' if request.htmx -> partial template more DRY. This mixin is far from perfect but it could be a start

**Comment by lolrenx** [comment]
This idea is credited to @malmiteria,  it makes the ol' if request.htmx -> partial template more DRY.  This mixin is far from perfect but it could be a start

**Comment by adamchainz** [comment]
Others have suggested but I'm not interested because this library aims to be like htmx - made of small features you compose, not end solutions.

Also partial rendering isn't the only way to use htmx, and possibly the least interesting - `hx-boost` or `hx-select` can achieve similar results with less effort.
