### ISSUE TITLE
Backend handling of hx-select

### ISSUE THREAD

**Issue by BoPeng** [adamchainz/django-htmx#243]
I have been using `htmx` for a while and developed a pattern in using

```
href="#" hx-get="some_url" hx-swap="innerHTML"
    hx-target="#content-wrapper" hx-select="#content"
    hx-push-url="true" 
```
I used a wrapper for `#content` due to [this problem](https://github.com/bigskysoftware/htmx/issues/786)  of using `outerHTML` to swap `#content` directly.

The advantage of this approach is that
1. If `some_url` is requested directly (non-htmx), the entire page will be displayed.
2. If `some_url` is requested through htmx, the content outside of `#content-wrapper` will be ignored, so the page will not be refreshed and flick.

This overall works well but I am wondering if the backend can be more clever in handling `hx-target`. Namely, if the `request.htmx` is `True` and there is `hx-target`, only the target portion will be returned to the frontend, which could, at least in theory, reduce the network traffic and burden of frontend.

This could be done explictly as follows:

1. At the template level, with templates `entire_page.html` defined as

```html
{% extends "base.html" %}
{% include "partial.html"%}
```

2. In the view function, process `htmx` request as follows
```python
if request.htmx:
    # also test hx-target if needed
    return render('partial.html')
return render('entire_page.html')
```

This can be done but it is difficult to maintain since it requires the frontend and backend to work together (e.g. change of `hx-target` selector, change of `partial.html`). I am therefore wondering if the same can be achieved at the middleware level through `django-htmx`.

The middleware will post-process `HttpResponse` to remove content outside of `hx-target`. Things can be a little complicated with
1. Complex `hx-select` target. The middleware could ignore `hx-target` that is not `#id` and pass the more complicated cases to the frontend.
2. `hx-swap-oob`, not sure how to do this, but again we can pass pages with `hx-swap-oob` to the frontend.
3. caching problem with some cache system since the backend returns different content for the same URL. I am not familiar with cache so cannot comment.

Does this sound like a valid feature to implement in `django-htmx`? I suppose that the biggest problem could be that the middleware is difficult to implement (parsing `HttpResponse`) and introduces bugs that are difficult to debug (frontend not receiving content as expected).

**Comment by adamchainz** [comment]
Parsing HTML to select a limited part of it could be very slow if not done with an efficient parser, such as [lol-html](https://github.com/cloudflare/lol-html) (i.e. not in Python). It's also wasteful to generate HTML and throw it away later in a middleware, especially since Django's template engine is [relative slow](https://tomforb.es/just-how-slow-are-django-templates/). I think it's better to focus on ways to swap the base template, as shown in the partial rendering demo in the example app.
