### ISSUE TITLE
Question: how secure is the debug script?

### ISSUE THREAD

**Issue by SHxKM** [adamchainz/django-htmx#257]
### Description

The `debug` script is super useful, however, since I don't know the internals of `htmx-django` and how exactly is `debug` `on/of` inferred, I'm wondering how secure it is.

Currently this is what I have in my `base.html`:

```HTML
<head>
    {% django_htmx_script %}
    <script src="{% static 'javascripts/htmx/htmx.min.js' %}" defer></script>
    <script src="{% static 'javascripts/hyperscript/hyperscript.min.js' %}"></script>
</head>

<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}' hx-ext="debug">...</body>
```

Is this safe? the documentation does not state `hx-ext="debug"` should be only be included if `{{ debug }}` is `on`. Where does that check happen?

**Comment by adamchainz** [comment]
The script is only output when `settings.DEBUG` is true, so it's not a security concern. It also cannot display any information that isn't already presented to the browser.

`hx-ext=debug` is a different debug tool, an extension that comes with htmx: https://htmx.org/extensions/debug/ . If you aren't including the extension's script on the page, `hx-ext=debug` will do nothing. That extension has no security concerns either as it only logs events in the browser that are already there.

**Comment by SHxKM** [comment]
Thanks for your answer and work @adamchainz!

**Comment by adamchainz** [comment]
I've just pushed 34cf34dc7d99e7004fcd2193c4704f7a81d13a8c to try and clarify the documentation.

**Comment by SHxKM** [comment]
Super. I was confused indeed. 

P.S.: HTMX + this + Hyperscript have already transformed the way I’m able to write UI/UX stuff. Amazing work.
