### ISSUE TITLE
Add relative current_url

### ISSUE THREAD

**Issue by treyhunner** [adamchainz/django-htmx#259]
### Description

`current_url` returns the full URL:

```pycon
>>> request.htmx.current_url
'https://www.pythonmorsel.com/some-page/
```

I'd like a way to access just the non-domain part of this URL (I'm using it for a `?next=` login redirect).

```pycon
>>> request.htmx.relative_current_url
'/some-page/
```

I imagine something like this might work.

```python
    @cached_property
    def relative_current_url(self) -> str | None:
        url = self.current_url
        if url:
            urlunparse(urlparse(url)._r(scheme='', netloc=''))
        return url
```

**Comment by adamchainz** [comment]
I wouldn't feel comfortable just dropping the origin, as it's potentially security-relevant information. Some projects are deployed with multiple origins.

Instead, why not compare with absolute URL's? I don't quite know what you're trying to do, but perhaps you could use something like this:

```python
if request.htmx.current_url == request.build_absolute_uri('/login/'):
```

**Comment by adamchainz** [comment]
Yeah I think adding the helper is probably too niche/security sensitive to solve here. Calling Django’s `redirect_to_login` to generate a response that you then just use the URL from doesn't sit right.

> (Django gets upset when it's an absolute URL).

How exactly? `redirect_to_login()` doesn't seem to mind. The later “allowed redirect” check should be done by the internal function `url_has_allowed_host_and_scheme()`, which checks for an allowed origin, so it should be fine with absolute URL's on the same origin?

(P.S. you probably want to use `urlsplit()` instead of `urlparse()`, as I [learned recently](https://www.youtube.com/watch?v=ABJvdsIANds). Django could probably do with that as well...)

**Comment by treyhunner** [comment]
> Yeah I think adding the helper is probably too niche/security sensitive to solve here. Calling Django’s `redirect_to_login` to generate a response that you then just use the URL from doesn't sit right.

I do agree that the specific use case I showed is a hack that isn't wise. That was the first case that came up and I haven't yet refactored that code.

I just came across another case today though.

Something like this in a non-HTMX Django page:

```html
{% url "users:login" %}?next={{ request.get_full_path }}
```

Doesn't have an equivalent in django-htmx land without a custom template filter/tag.

```html
{% url "users:login" %}?next={{ request.htmx.relative_current_url }}
```

> > (Django gets upset when it's an absolute URL).
> 
> How exactly? `redirect_to_login()` doesn't seem to mind. The later “allowed redirect” check should be done by the internal function `url_has_allowed_host_and_scheme()`, which checks for an allowed origin, so it should be fine with absolute URL's on the same origin?

From my testing, passing an absolute URL to `next=` didn't seem to work.
Django seems to just ignore the `next` value entirely when it wasn't a relative URL (as of Django 3.2 at least).


> (P.S. you probably want to use `urlsplit()` instead of `urlparse()`, as I [learned recently](https://www.youtube.com/watch?v=ABJvdsIANds). Django could probably do with that as well...)

Ah I do. Thanks for noting that!

**Comment by adamchainz** [comment]
Added in #287, as `current_url_abs_path`.

I did and a bit of research to check naming, and was reminded that relative URL’s mean “relative to a given base URL`, like `./image.png` is relative to whichever URL. The right name is “absolute-path” as per [section 4.2 of this RFC](https://www.rfc-editor.org/rfc/rfc3986#page-26), which is also what Django (kinda) uses e.g. in `Model.get_absolute_url()`. So I picked the name with the `_abs_path` suffix, which is kinda wordy but at least correct.
