### ISSUE TITLE
TypeVars in documentation

### ISSUE THREAD

**Issue by cjtapper** [adamchainz/django-htmx#265]
### Package Version

1.12.2

### Description

![image](https://user-images.githubusercontent.com/5920765/187873874-186a0398-3542-4c1d-8da2-bb14640cb68a.png)

Is there a better way to annotate these types so that the docs are more informative? I'm relatively new to typing and am unsure of what the best way to do this is. Should we just rename `_R` to something like `_HttpResponse`?

**Comment by adamchainz** [comment]
Good spot. I know people are disussing ways of improving sphinx's output here, but for now it's pragmatic to use a more explicit typevar name. It will help in text editors that use the hints as well. #266 changes the name.
