### ISSUE TITLE
Support for adding vary headers

### ISSUE THREAD

**Issue by benhowes** [adamchainz/django-htmx#300]
### Description

When one uses a single URL for both HTMX and non htmx responses, it can confuse the browser in to caching HTML fragments for a URL rather than the whole page when that URL has been requested on load, and then subsequently by HTMX. The fix suggested [over here](https://github.com/bigskysoftware/htmx/issues/724) is to use the HTTP `Vary` header.

As such I have a small custom middleware, which I wondered about if it would make sense to combine with the main `django-htmx`, probably with a setting to control it.

My current extra middleware:

```python
def htmx_vary_header_middleware(get_response):
    """Middleware that adds `HX-Request` to the vary headers to prevent browser caching
    html fragments when a URL can return full pages, or HTMX fragments."""

    def middleware(request):
        response = get_response(request)
        patch_vary_headers(response, ("HX-Request",))
        return response
```

Happy to make a PR if there is any interest?

**Comment by adamchainz** [comment]
This is unfortunately just something you have to handle when you add HTTP caching, not really something that can be generally automable. You have to handle it on a case-by-case basis, for all headers that may affect a view.

Even when using htmx, not all views will change their content based on htmx headers (perhaps not even most). And then they could vary based on any of the other htmx headers. So I don't think there's anything we can do in the library.

**Comment by benhowes** [comment]
Thanks for the response and I agree with your decision on reflection. All the best!
