### ISSUE TITLE
request.htmx.current_url_abs_path unexpectedly returns None

### ISSUE THREAD

**Issue by Snakeyyy** [adamchainz/django-htmx#309]
### Python Version

3.10.6

### Django Version

4.1

### Package Version

1.13.0

### Description

Below is the implementation for context: 
```
    def current_url_abs_path(self) -> str | None:
        url = self.current_url
        if url is not None:
            split = urlsplit(url)
            if (
                split.scheme == self.request.scheme
                and split.netloc == self.request.get_host()
            ):
                url = urlunsplit(split._replace(scheme="", netloc=""))
            else:
                url = None
        return url

```
Problem: 

When the application server is behind a proxy like Nginx it can happen that condition `split.scheme == self.request.scheme` is False (request.scheme has value http while split.scheme has value https).

I'm not sure what's the purpose of these conditions checks. Eventually, I would suggest to remove these checks.

**Comment by adamchainz** [comment]
Do you have `SECURE_PROXY_SSL_HEADER` correctly configured?

https://docs.djangoproject.com/en/4.1/ref/settings/#secure-proxy-ssl-header

**Comment by adamchainz** [comment]
Closing due to lack of reply.
