### ISSUE TITLE
I am working on a awesome-python-htmx, seeking your feedback

### ISSUE THREAD

**Issue by benjamin-kirkbride** [adamchainz/django-htmx#329]
### Description

A few of us at PyCon this year got together and brainstormed a new Web Stack that we are calling PyHAT (Python, htmx, ASGI, TailwindCSS). The first thing we set out to do is create [awesome-python-htmx](https://github.com/PyHAT-stack/awesome-python-htmx/blob/main/README.md); a collection of active tools/libraries/projects in that space.

Your project seems like an obvious thing to include, so I did. I'd appreciate your feedback if you have any on it's inclusion.

In addition to that, if you could also participate in PyHAT-stack/awesome-python-htmx#1 that would be greatly appreciated!

**Comment by adamchainz** [comment]
Hi!

Thanks for reaching out and mentioning django-htmx.

Small feedback: I'm not sure it's useful for the framework labels next to project names (Django, Starlette, etc.) to link to the framework pages. Makes the link target a bit less obvious, and may make readers think that e.g. django-htmx is part of Django.

As for contributing more to the group: I'm not a fan of Tailwind, and I think async Python is too complex for 90% of sites. So I'm not sure I fit in, but good luck!

**Comment by benjamin-kirkbride** [comment]
Thanks for the feedback!
