### ISSUE TITLE
@htmx_only decorator

### ISSUE THREAD

**Issue by cpa** [adamchainz/django-htmx#330]
### Description

I find myself frequently using a htmx_only decorator in my projects for requests that do not push to history on the client-side (hx-push-url="false"). While I am not a strict adherent to HATEOAS principles, such a decorator still aligns with them imo. 

Regarding what should be done when a request is not an htmx one, I think that returning an HTTP 400 or 412 (I currently use 400) would be appropriate.

If a htmx_only decorator would be a useful addition to django-htmx, I am willing to submit a pull request.

**Comment by bittner** [comment]
> It doesn't offer any security or UX improvements.

Interesting. I would have said the opposite is an obvious conclusion. Agreed, w.r.t. application security, blocking unwanted calls doesn't close holes in a vulnerable application, but it makes the implementation cleaner when we allow intended use only. Also imagine URLs indexed by a search engine: People landing there are certainly not amused.

> loading up a fragment URL can be useful, at least for debugging with webdev tools or django-debug-toolbar

@valberg suggested to allow loading a fragment when `DEBUG=True` in https://github.com/adamchainz/django-htmx/issues/205#issuecomment-1066485414. I feel that might be a good idea.

**Comment by adamchainz** [comment]
You're always free to implement such a decorator in your projects. I remain unconvinced to add one to this package.
