### ISSUE TITLE
Add a section for testing in the docs

### ISSUE THREAD

**Issue by eduzen** [adamchainz/django-htmx#344]
### Description

Hi @adamchainz, thank you for this package! I am trying to use it and I don't know how to test my views 🤔 . 

I tried to do something like:
```
response = self.client.post(
    self.url, 
    data={}
    headers={"HTTP_HX_REQUEST": "true"},
)
```

But when it goes to the view, this if it is not working:

```
if not request.htmx:  # type: ignore
    return HttpResponseRedirect(some_url)
```

What I'm doing wrong 🙃 ?  I would like to learn and also help you to add it to the docs. Also, you will notice the type ignore. Maybe that needs a section in the docs too?

**Comment by adamchainz** [comment]
You're mixing up header syntax between Django 4.1 (`HTTP_HX_REQUEST`) and Django 4.2's `headers` arg (which takes just the headers: `HX-Request`).

Try:

```python
response = self.client.post(
    self.url, 
    data={},
    headers={"HX-Request": "true"},
)
```

We could add a testing section to the docs, but asides from one example like this, I'm not sure what else we could add?

**Comment by eduzen** [comment]
Thanks for the quick response @adamchainz . You are right, nothing else pop to my mind.

**Comment by Mte90** [comment]
Just find this for the same reason. I think that can be helpful for a newcomer some example following the official django doc about testing and showing what are the differences to tests the views by django-htmx.

**Comment by adamchainz** [comment]
If you want to open a PR with an example for the above pattern, sure. But I don’t think we need much content beyond “here’s how to set the headers”.
