### ISSUE TITLE
Relative Path Shortcut

### ISSUE THREAD

**Issue by kdmwangi** [adamchainz/django-htmx#368]
### Description

I think the shortcut for the relative url path, is somehow named `current_url_abs_path` in the middleware. But inside the templates the wrong method is invoked. probably be `{{ request.htmx.current_url_abs_path|stringformat:'r' }}`.

Correct me if I am wrong,
Thanks

**Comment by adamchainz** [comment]
The name was picked for a specific reason: https://github.com/adamchainz/django-htmx/issues/259#issuecomment-1310079665 . According to URL standards it's not “relative”, but “absolute”.

I don’t understand what you mean by “inside the templates the wrong method is invoked”. Templates call the same functions as normal Python code. If you can provide a full failing example that would be appreciated.

**Comment by kdmwangi** [comment]
`   <tr>
      <td><code>request.htmx.current_url</code></td>
      <td><code>{{ request.htmx.current_url|stringformat:'r' }}</code></td>
    </tr>
    <tr>
      <td><code>request.htmx.current_url_relative</code></td>
      <td><code>{{ request.htmx.current_url_relative|stringformat:'r' }}</code></td>
    </tr>
    <tr>`

this is actually what mean i dont know if its mixup on the shortcut, inside example app templates

**Comment by kdmwangi** [comment]
#259 I have gone through the issue but i dont see how the shortcut is demonstrated in the example app(forgive my inability to express it clearly)
