### ISSUE TITLE
Load script  via htmx and execute

### ISSUE THREAD

**Issue by jacopsd** [adamchainz/django-htmx#372]
### Description

Typically the main part of a page has some html, and also might require some js code.

This js code can be referrenced from another server, or included as a script source.

How can such html code + script be loaded and executed via via htmx? So after the html is placed n the DOM, the js needs to be executed.

**Comment by adamchainz** [comment]
This is an htmx question, not a django-htmx question, so you’ve posted it in the wrong place.

But the short answer is that htmx runs `<script>` tags within source unless [`htmx.config.allowScriptTags`](https://htmx.org/docs/#configuration-options) is disabled.
