### ISSUE TITLE
variation on django_htmx_script - load error into target, instead of replacing whole page

### ISSUE THREAD

**Issue by gabriel-v** [adamchainz/django-htmx#375]
### Description

The `django_htmx_script` override updates, on error, the whole page.

One could instead do something else, which is to only replace the error swap target with the error page.

The Iframe is necessary to avoid stylesheets polluting the outer page.

To try it out, replace the [event listener](https://github.com/adamchainz/django-htmx/blob/d8eb8ec3ea3f88e775d7a51e057fc50a78be3cf6/src/django_htmx/static/django-htmx.js#L6C15-L6C15) with this:

```
document.body.addEventListener("htmx:responseError", function(e) {
    error_html = e.detail.xhr.response;
    // This is bad: the CSS from django error page will be applied to whole DOM!
    // e.detail.target.innerHTML = error_html;

    var iframe = document.createElement('iframe');
    iframe.srcdoc = error_html;
    iframe.style = "height: 400px; width: 700px; resize: both; overflow: auto;"
    e.detail.target.appendChild(iframe);
    e.detail.target.classList.remove("visually-hidden");
});
```

Question:
- is there any other configuration or events that would need to be overridden to cover other errors currently covered by django_htmx_script?

**Comment by adamchainz** [comment]
I’m not a fan of this because there’s no guarantee the iframe will be readable, even after trying to force it to a minimum size with CSS. It could still be hidden or off screen.

The current behaviour is clear, even if it feels a little drastic.
