### ISSUE TITLE
Support more than just "true" as value for boolean request headers

### ISSUE THREAD

**Issue by jnns** [adamchainz/django-htmx#383]
The [documentation for HtmxDetails](https://django-htmx.readthedocs.io/en/latest/middleware.html#django_htmx.middleware.HtmxDetails) currently states that `request.htmx` will evaluate to `True` if the respective header is set, although the value is actually required to be `'true'`. 

This tripped me off when I was writing a test case that used `client.get(url, headers={'HX-Request': True})`. This is no big deal at all, but I assumed that it would already work if the header is present, regardless of its actual value. 

Should we change `__bool__`, `boosted` and `history_restore_request` to always return True if the header is present, or also accept `'True'`, `'on'` and `'1'` as well, or instead state in the docs that the header's value needs to be `'true'` ?

**Comment by adamchainz** [comment]
> This tripped me off when I was writing a test case that used `client.get(url, headers={'HX-Request': True})`. This is no big deal at all, but I assumed that it would already work if the header is present, regardless of its actual value.

Just to be explicit: Django calls `str()` on all header values, so this will be `True`.

> Should we change `__bool__`, `boosted` and `history_restore_request` to always return True if the header is present, or also accept `'True'`, `'on'` and `'1'` as well, or instead state in the docs that the header's value needs to be `'true'` ?

I think we should be true to htmx and only support `'true'`, docs updated in #384.

**Comment by jnns** [comment]
> Django calls str() on all header values, so this will be True.

That's right, but `'True' != 'true'`. 

Thank you for implementing this change so quickly! 🚀
