### ISSUE TITLE
Template tag?

### ISSUE THREAD

**Issue by skorokithakis** [adamchainz/django-htmx#389]
### Description

I have to admit that I haven't used HTMX as much as I'd like, but one thing seems to be missing perhaps: A template tag that will render a partial instead of the entire page.

Please correct me if I'm wrong, but it seems a bit cumbersome to have different base templates for every single page so you can render snippets of things. Wouldn't a template tag that returns just the bits that HTMX needs, depending on whether the view was requested via HTMX or not, be a good addition?

**Comment by adamchainz** [comment]
This idea has been floated in several places in Django’s history, not just in the context of htmx. The most prominent example of such a template tag is [django-template-partials](https://github.com/carltongibson/django-template-partials). Hopefully something will get added to Django core at some point.
