### ISSUE TITLE
Add support for hx-replace-url

### ISSUE THREAD

**Issue by limugob** [adamchainz/django-htmx#405]
### Description

Hello Adam, 
thanks for this lib.
I would like to use [hx-replace-url](https://htmx.org/attributes/hx-replace-url/) through django-htmx and have implemented it in #396.

What do you think?

**Comment by adamchainz** [comment]
Don’t open an issue for an existing PR. I will review when I can.

**Comment by limugob** [comment]
Sorry, I was not sure, what the right way is.
