### ISSUE TITLE
Getting CSRF errors with Middleware tests

### ISSUE THREAD

**Issue by jbarham** [adamchainz/django-htmx#41]
Thanks for this app and demo code!

I configured and ran the example app per the instructions, but get CSRF errors when trying to use the _Middleware Tester_ page buttons & input. Log output is the following:
```
Forbidden (CSRF token missing or incorrect.): /middleware-tester/table/
[16/Feb/2021 01:59:07] "PUT /middleware-tester/table/ HTTP/1.1" 403 2513
```
This error goes away if I add the CSRF token to the test buttons and input in `middleware-tester.html`, e.g.:
```
        <button id="basic-button"
                hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                hx-put="/middleware-tester/table/">
          Basic button
        </button>
```
I'm running on Ubuntu. I get the same CSRF error whether using Firefox, Chrome or Brave.

**Comment by adamchainz** [comment]
An oversight when adding the CSRF demo. Thanks for the clear report, fixed in #41.
