### ISSUE TITLE
Request: Add short description to the readme or documentation that explains why to use this package. 

### ISSUE THREAD

**Issue by kicksent** [adamchainz/django-htmx#438]
### Description

What does this package do that django + htmx doesn't do out of the box? 

This repo https://github.com/PyHAT-stack/web-async-patterns uses django and htmx but doesn't seem to use this package. 

It's not immediately clear when or why I would add this middleware. 

Adding a few sentences to the documentation page or readme would help to make this more clear. 

Thanks!

**Comment by adamchainz** [comment]
I’m open to suggestions but I think the tagline is kinda clear (“Extensions for using Django with htmx.”) and the feature pages in the docs let you know what you get.

**Comment by adamchainz** [comment]
I’ve added a clarifying sentence on the front page of the docs in #469.
