### ISSUE TITLE
Multiple HX-Trigger Response Headers

### ISSUE THREAD

**Issue by JulianS-Uni** [adamchainz/django-htmx#443]
### Description

The [htmx doc](https://htmx.org/headers/hx-trigger/) describes that it is possible to invoke multiple events from one HX-Trigger header (scroll to the bot). As far as i read your documentation right and asfar as I can tell from your source code this is not supporter by trigger_client_event() can you have a look into this and add this feature?

**Comment by adamchainz** [comment]
The [docs say](https://django-htmx.readthedocs.io/en/latest/http.html#django_htmx.http.trigger_client_event):

> Calling trigger_client_event multiple times for the same response and after will update the appropriate header, preserving existing event specifications.

Meaning: call it multiple times to trigger multiple events. If you want to suggest a clarification, please open a PR.
