### ISSUE TITLE
Extend HttpResponseLocation to Support select Attribute

### ISSUE THREAD

**Issue by NikolaAnovic** [adamchainz/django-htmx#461]
### Description

I would like to propose an enhancement to the `HttpResponseLocation` class. Currently, this class provides a way to handle HTTP responses with location headers, primarily supporting URL redirection. However, the HTMX library also supports a select element as part of the hx-location feature, which allows for more dynamic client-side redirections.

**References**
•	[HTMX hx-location documentation](https://htmx.org/headers/hx-location/)
•	[django-htmx HttpResponseLocation source code](https://django-htmx.readthedocs.io/en/latest/_modules/django_htmx/http.html#HttpResponseLocation)

I am willing to implement this feature and submit a pull request for review.

**Comment by adamchainz** [comment]
Great, this was added to htmx later per https://github.com/bigskysoftware/htmx/pull/2022 . Reviewing PR now.
