### ISSUE TITLE
'select' kwarg support in HttpResponseLocation

### ISSUE THREAD

**Issue by Nizzy94** [adamchainz/django-htmx#465]
### Python Version

3.12

### Django Version

5.0.2

### Package Version

1.18.0

### Description

I read the issue #461 and it was closed because the problem was claimed to be resolved. It hasn't been solved for me.
I was using version 1.17.2 when I realised the select kwarg was not supported. so I upgraded to 1.18.0, which in the documentation and source code shows the select kwag as part of the options.

when I hover over the one in my code, it doesn't show the select options, causing my code to fail. Without it, I would have to restructure a lot of code for it to work. below is a screenshot of the hover:

![Screenshot 2024-08-03 at 1 27 24 AM](https://github.com/user-attachments/assets/3128dd50-1651-42d4-9530-f15fefd1ed7a)

below is the screenshot of the version I currently upgraded to:

![Screenshot 2024-08-03 at 1 31 08 AM](https://github.com/user-attachments/assets/04a056f1-6f19-4b85-8497-bf5c41075306)

![Screenshot 2024-08-03 at 1 31 44 AM](https://github.com/user-attachments/assets/7538f00f-a564-494c-9187-30d3ade04b91)

**Comment by adamchainz** [comment]
It hasn't been released yet, sorry for any confusion. The latest docs are for the latest commit not latest release.

**Comment by Nizzy94** [comment]
Ok. thank you
