### ISSUE TITLE
Searching through table breaks after search

### ISSUE THREAD

**Issue by xtlc** [adamchainz/django-htmx#48]
I tried to combine the example code with the [htmx active search](https://htmx.org/examples/active-search/) example. The example looks fairly easy, just switching the content of the table body after the search.

I am not sure on how to proceed here to achieve something similar to the regex search for example in datatables.net. Easy example with a model with two fields `title` and `description`:

```
class IndexView(TemplateView):
    template_name = "app/index.html"

    def post(self, request, *args, **kwargs):
        search = request.POST["search"]
        result = Order.objects.filter(Q(description__icontains = search) | Q(title__name__icontains = search))
        page = Paginator(object_list = result, per_page = 25).get_page(1)
        return render(request, "app/partial-rendering.html", {"base_template": "app/_partial.html", "page": page,},)

    def get(self, request, *args, **kwargs):
        orders = Order.objects.all()
        page_num = request.GET.get("page", "1")
        page = Paginator(object_list = orders, per_page = 25).get_page(page_num)
        if request.htmx:
            base_template = "app/_partial.html"
        else:
            base_template = "app/index.html"
        return render(request, "app/partial-rendering.html", {"base_template": base_template, "page": page,},)

```
The code I use for searching and the table:

```
<input class="form-control" 
       type="text" 
       name="search" 
       placeholder="search for orders..." 
       hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
       hx-post="/" 
       hx-trigger="keyup changed delay:500ms" 
       hx-target="#search-results" 
       hx-indicator=".htmx-indicator">

<main role="main" id="main">
    <table>
            <thead>
                <tr>
                    <th>title</th>
                    <th>escription</th>
                </tr>
            </thead>
            <tbody id="search-results">
                {% for item in page.object_list %}
                    <tr>
                        <td>{{ item.title}}</td>
                        <td>{{ item.description }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
</main>
```
I do get the right results, but appended to the first `<table>` element as whole new table (because this is what  `post` method returns obviously).

How do I use the search example correctly in my table, so that only the found items are shown AND so that I can keep using the prev/next page buttons on the buttons while the search is "active"? I am happy to provide my code for the example, once working.

**Comment by adamchainz** [comment]
Don't use POST but GET, and merge the code for the pagination and the search all into the GET path on your view. Then use the HX-Push header to change the URL in responses to include the search and page query parameters.

Hope that helps!
