### ISSUE TITLE
hyperlink w/target="_blank" and hx-boost="false" is being reported as a boosted link

### ISSUE THREAD

**Issue by bschollnick** [adamchainz/django-htmx#484]
### Python Version

3.12.5

### Django Version

5.1.1

### Package Version

1.19.0

### Description

I'm attempting to open the next page in a new window/tab, using target="_blank" in the hyperlink, e.g.:

 <p align=center hx-boost="false">
        <a href="/viewer2/{{ next_uuid }}" hx-boost="false" id="next_tab_uuid" target="_blank">
                        {{ icon('fas fa-external-link-alt fa-3x') }}</a></p>

My view logic is based entirely around the request.htmx.boost boolean:

```
   if request.htmx.boosted:
        print("partial")
        template_name = "frontend/gallery_htmx_partial.jinja"
    else:
        print("full")
        template_name = "frontend/gallery_htmx_complete.jinja"
    if not filetypes.models.FILETYPE_DATA:
        print("Loading filetypes")
        filetypes.models.FILETYPE_DATA = filetypes.models.load_filetypes()
    i_uuid = str(i_uuid).strip().replace("/", "")
    context = build_context_info(request, i_uuid) | {"user": request.user} # | {"sort": sort_order(request), "uuid": i_uuid, }
    response = render(
        request, template_name, context, using="Jinja2"
    )
    return response
```

This link is being shown as boosted, even though hx-boost is set false.  I'm unclear if this is a htmx issue, or a django-htmx issue.  How can I troubleshoot this further, to help identify what is causing this issue?

**Comment by adamchainz** [comment]
`request.htmx.boost` only reads the header from htmx. It sounds like an htmx issue that it's sending the header despite your request not to do that.

Remember that htmx attributes are inherited, so if you put `hx-boost="true"` somewhere high in the DOM tree, it applies to all links below.
