### ISSUE TITLE
ModuleNotFoundError: No module named 'django_htmx'

### ISSUE THREAD

**Issue by dgchrt** [adamchainz/django-htmx#487]
### Python Version

3.10.5

### Django Version

5.0.7

### Description

Running the `example` code causes a:
```sh
ModuleNotFoundError: No module named 'django_htmx'
```

It runs fine after manually installing the missing dependency via:
```sh
pip install django-htmx
```

I believe `django-htmx` is missing in the requirements files, so that the example can run out of the box.

**Comment by adamchainz** [comment]
I think you missed the `-e ..` from the install step in the instructions. That is the bit that installs django-htmx as editable (`-e` = editable install, `..` = the folder above).

Try again, it should work :)

**Comment by dgchrt** [comment]
You're right, I completely overlooked that. Thanks for clarifying it. :)
