### ISSUE TITLE
Modal Create/Update example

### ISSUE THREAD

**Issue by xtlc** [adamchainz/django-htmx#49]
Is it possible mixing HTMX using django-htmx for a modal create/update dialog [htmx-modal-dialog-example](https://htmx.org/examples/modal-custom/) without a page refresh?

I would appreciate if you throw me a bone:

```
    <button 
        id="showButton"
        hx-get="/create" 
        hx-target="#modals-here" 
        class="uk-button uk-button-primary" 
        _="on htmx:afterOnLoad wait 10ms then add .uk-open to #modal">Open Modal
    </button>

<div id="modals-here"></div>
```
simple form / createview / urls.py entry:

```
class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ("description", "price",)

class CreateProductView(TemplateView):
    def get(self, request, *args, **kwargs):
        return render(request, "app/product_create.html", {'form': ProductForm})

path("create/", views.CreateProductView.as_view(), name = 'create'),
```

What I did now is, that i used the DRF API to POST new products into the database, which is obviously not recognized by htmx (but this way via AJAX I can avoid a reload). I also feel kind of guilty, because I had to use a second view (I wanted to use my normal view, but there is no way to send a "name" attribute via hx-get in a button to the view).
So ... two questions and a request in the end for this cool little extension:

- how would I trigger an update of a section after my AJAX update?
- Is it possible to send a name to the get like in an <input> field with hx-get?
- I feel like I did not really use the whole magic of htmx here and a modal example would be very helpful!

**Comment by adamchainz** [comment]
> there is no way to send a "name" attribute via hx-get in a button to the view

You can use hx-vals to send extra query params: https://htmx.org/attributes/hx-vals/

But a second view is the right approach!

>  i used the DRF API to POST new products into the database

Just make a normal view that returns HTMl. That's what HTMX is looking for and it can still use it without a page reload. There's no need to use JSON.

As a design pattern I try to avoid modals. I prefer placing standalone forms on their own pages so they have their own URL's, obey the forwards/back buttons, etc. Because of this, and how good the htmx modal page is, I'll skip adding an example here.

Hope that helps,

Adam

**Comment by xtlc** [comment]
Thanks about the reassurance with the second view. 

Tried to get it working with a second template view, but I struggle to update the htmx part:
``` 
class CreateProductView(TemplateView):
    def get(self, request, *args, **kwargs):
        return render(request, "app/product_create.html", {'form': ProductForm})
    
    def post(self, request):
        Product.objects.create(...)
        return render(request, "app/index.html")
```
this way I can post data without using the DRF, but I still do not see immediately the updates posted.

**Comment by adamchainz** [comment]
Your response contains HTML, so if it's working then htmx can place that HTML in the DOM. Try debugging with your browser's devtools to see what happens in the network/DOM tabs. Also you can try the htmx debug mode: https://htmx.org/docs/#debugging
