### ISSUE TITLE
 HttpResponseLocation affected by bug in HTMX 2.0.3

### ISSUE THREAD

**Issue by jhh** [adamchainz/django-htmx#497]
### Python Version

3.12.7

### Django Version

5.1.3

### Package Version

1.21.0

### Description

Submitting this issue to track a bug in HTMX 2.0.3 that others might see after upgrading HTMX. The HTMX client will not submit a redirected request when using `HttpResponseLocation`.   See bigskysoftware/htmx#2958.

The fix appears to have been merged and should be in the 2.0.4 HTMX release.

**Comment by adamchainz** [comment]
Please don't reflect issues here, I don't think that's helpful, it's just spamming me as maintainer.
