### ISSUE TITLE
Missing django-htmx dependency in example

### ISSUE THREAD

**Issue by tomwojcik** [adamchainz/django-htmx#57]
[`requirements.txt`](https://github.com/adamchainz/django-htmx/blob/cda60d6ab6bf2a7abe9ba709f75e6c582546eb1b/example/requirements.txt) from the example app are missing `django-htmx` dependency.

**Comment by adamchainz** [comment]
This is on purpose. If you follow its setup instructions, the line `python -m pip install -r requirements.txt -e ..` will install django-htmx from the local copy (the `-e ..` bit).

**Comment by tomwojcik** [comment]
Ahh, got it
