### ISSUE TITLE
 Thank you for Creating Django specific HTMX project. 

### ISSUE THREAD

**Issue by inayet** [adamchainz/django-htmx#82]
if possible can you guys create a video tutorial using a django app with htmx? the django app can be new meaning you create a new django project and then use htmx  for the frontend, or refactor a django app using htmx for the frontend. I learn best by watching, reading, and practicing.

**Comment by adamchainz** [comment]
Great that this has helped you. You can follow my blog ( https://adamj.eu/tech/ ) for any content I write, about Django etc. In the future I hope to write about using htmx with Django, and may do videos if there's enough demand.
