### ISSUE TITLE
WSGI Error.    

### ISSUE THREAD

**Issue by flamaso** [adamchainz/django-htmx#9]
Hello!

i was successful with your /demo.   but when i start a new django app and do this middleware change, it gives me an Error (WSGI..) .     i am the only one? :) 

Add the middleware:

MIDDLEWARE = [
    ...,
    "django_htmx.HtmxMiddleware",
    ...,
]

**Comment by adamchainz** [comment]
This package is not the code that is on PyPI yet. We're in the process of merging the two efforts in #5 and aftert that there will be a release where this package is on PyPI.
